@startuml
package "Investidor" {
  (Login)
  (Dashboard do Investidor)
  (Realizar Pagamento)
  (Visualizar Risco de Projeto)
  (Download dos Documentos de Oferta)
  (Descobrir Investimentos)
}

package "Empreendedor" {
  (Login)
  (Preencher Formulário de Projeto)
  (Upload de Documentos)
  (Gerenciar fases do projeto)
  (Dashboard do DP)
}

package "Administrador" {
  (Login)
  (Visualizar dados dos usuários)
  (Assegurar Conformidade)
  (Supervisionar Registro de Incorporação)
  (Dashboard do ADM)
  (Aprovar projetos)
}

package "Sistema" {
  (Registro de usuário)
  (Esqueci a senha)
  (Notificação de oportunidades para investidores)
}
@enduml
