@startuml
actor "Desenvolvedor de Projetosr" as DP
DP -> (Preencher Formulário de Projeto)
(Preencher Formulário de Projeto) -> (Entra com detalhes do prtojeto) : <<include>>
(Preencher Formulário de Projeto) -> (Validaçao dos dados) : <<include>>
(Validaçao dos dados) --> (Envio do Projeto)
@enduml
